[package]
authors = ["svorr <svorre2304@gmail.com>"]
edition = "2021"
name = "extractor"
version = "0.1.0"


[dependencies]
pdb = "0.7.0"
clap = "3.0.0-beta.4"
log = "0.4.14"
env_logger = "0.9.0"
anyhow = "1.0.42"

[dependencies.winapi]
version = "0.3.9"
features = [
	"winnt",
]